import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "./components/ThemeProvider"; // ruta según donde lo tengas
import { MenuProvider } from "../context/MenuContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio Franco",
  description: "Generated by Franco",
  metadataBase: new URL("http://localhost:3000"),
  openGraph: {
    title: "Franco Portfolio",
    description: "Portfolio profesional de Franco, desarrollador full stack.",
    url: "/",
    siteName: "Franco Portfolio",
    type: "website",
    images: [
      {
        url: "/og-image.png", // la ponés en /public
        width: 1200,
        height: 630,
        alt: "Imagen OG del portfolio de Franco",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <MenuProvider>
          {children}
          </MenuProvider>
        
      </body>
    </html>
  );
}
